version: '3.9'
services:

    airflow:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: airflow
        ports:
            - "8080:8080"
        networks:
            - bridge
        volumes:
            - code_forces_airflow:/usr/local/airflow:rw

    
    destination-db:
        image: epiclabs/docker-oracle-xe-11g
        container_name: destination
        ports:
            - "49161:1521"
        environment:
            - ORACLE_ALLOW_REMOTE=true
        networks:
            - bridge


networks:
    bridge:
        driver: bridge

volumes:
    code_forces_airflow:
        name: airflow
        driver_opts:
            type: none
            device: ./airflow
            o: bind
            